import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { FormProvider } from "@/context/Userinitial";
import { FormSearchProvider } from "@/context/SearchContext";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex flex-col min-h-screen max-h-screen">
          <FormProvider>
            <FormSearchProvider>
              <Navbar />
              <main className="flex-grow h-full">{children}</main>
              <Footer />
              <Toaster position="top-center"/>
            </FormSearchProvider>
          </FormProvider>
        </div>
      </body>
    </html>
  );
}
